// ****Experimenting. Trying to add a choice for selecting Prime Field of interest*** 


// Reference: https://github.com/summa-dev/summa-solvency/blob/90c4242840b04122e699d07c009f4e233a223663/zk_prover/src/chips/poseidon/poseidon_spec.rs

//! This file was generated by running generate_params.py
//! Specification for rate 1 Poseidon using the BN256 curve.
//! Patterned after [halo2_gadgets::poseidon::primitives::P128Pow5T3]
use crate::hash::poseidon_params;
use halo2_gadgets::poseidon::primitives::*;
use halo2_proofs::arithmetic::Field;
use halo2_proofs::halo2curves::bn256::Fr as Fp;

#[derive(Debug, Clone, Copy)]
pub struct PoseidonSpec;

pub(crate) type Mds<Fp, const T: usize> = [[Fp; T]; T];

impl Spec<Fp, 2, 1> for PoseidonSpec {
    fn full_rounds() -> usize {
        8
    }

    fn partial_rounds() -> usize {
        56
    }

    fn sbox(val: Fp) -> Fp {
        val.pow_vartime([5])
    }

    fn secure_mds() -> usize {
        unimplemented!()
    }

    fn constants() -> (Vec<[Fp; 2]>, Mds<Fp, 2>, Mds<Fp, 2>) {
        (
            poseidon_params::ROUND_CONSTANTS[..].to_vec(),
            poseidon_params::MDS,
            poseidon_params::MDS_INV,
        )
    }
}